### PR TITLE
Update HUD Hint

### PR DESCRIPTION
**Pull request by franksmcb**
Change HUD Hint to Left ALT Key

### CODE REVIEW

**Comment by franksmcb** [comment]
Resolve https://bugs.launchpad.net/ubuntu-mate/+bug/1877603

**Comment by vkareh** [comment]
This helps a bit, but that key is configurable. I wonder if there's a benefit to having something like
```
When checked the Heads-Up Display (HUD) will be enabled. Press the configured key (defaults to Left Alt) to search application menus.
```

Also note that it should be `Left Alt`, rather than `Left ALT` (note the casing)

**Comment by franksmcb** [comment]
That makes more sense

**Pull request merged**
